name: Branch Flow Policy

on:
  pull_request:
    branches:
      - qa
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Validate branch flow
        run: |
          BASE="${{ github.base_ref }}"
          HEAD="${{ github.head_ref }}"

          if [ "$BASE" = "qa" ] && [ "$HEAD" != "dev" ]; then
            echo "❌ Only dev → qa allowed"
            exit 1
          fi

          if [ "$BASE" = "main" ] && [ "$HEAD" != "qa" ]; then
            echo "❌ Only qa → main allowed"
            exit 1
          fi

          echo "✅ OK"
